# Generated by Django 5.0.3 on 2025-10-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_customprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
