# Generated by Django 5.2.7 on 2025-10-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_customprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
