# Generated by Django 5.2.7 on 2025-10-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0002_remove_chat_members_chat_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
