# Generated by Django 5.2.7 on 2025-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0004_groupmessage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='bio',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
