# Generated by Django 5.2.7 on 2025-10-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_chat_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='bio',
            field=models.TextField(blank=True, max_length=9999, null=True),
        ),
    ]
