# Generated by Django 5.2.7 on 2025-10-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0005_rename_groupmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date']},
        ),
    ]
